apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pensjonskalkulator
  name: pensjonskalkulator-uinnlogget
  namespace: pensjonskalkulator
spec:
  image: {{image}}
  ingresses:
    - https://www.nav.no/pensjon/uinnlogget-kalkulator
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  replicas:
    min: 2
    max: 4
  liveness:
    path: /api/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /api/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  accessPolicy:
    outbound:
      rules:
        - application: pensjonskalkulator-backend
      external:
        - host: www.nav.no
  azure:
    application:
      enabled: true
