apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pensjonskalkulator
  name: pensjonskalkulator-uinnlogget-frontend
  namespace: pensjonskalkulator
spec:
  image: {{image}}
  ingresses:
    - https://www.nav.no/pensjon/uinnlogget-kalkulator
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  replicas:
    min: 2
    max: 4
  liveness:
    path: /pensjon/uinnlogget-kalkulator/internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /pensjon/uinnlogget-kalkulator/internal/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  accessPolicy:
    outbound:
      rules:
        - application: pensjonskalkulator-backend
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: www.g.nav.no
        - host: pensjonskalkulator-unleash-web.iap.nav.cloud.nais.io
  azure:
    application:
      enabled: true
  envFrom:
    - secret: uinnlogget-kalkulator-unleash-api-token
