apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pensjonskalkulator
  name: pensjonskalkulator-uinnlogget-dev
  namespace: pensjonskalkulator
spec:
  image: {{image}} # Placeholder variable to be replaced by the CI/CD pipeline
  ingresses:
    - https://pensjonskalkulator-uinnlogget-dev2.ekstern.dev.nav.no/pensjon/kalkulator-uinnlogget
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
  accessPolicy:
    outbound:
      rules:
        - application: pensjonskalkulator-backend
  azure:
    application:
      enabled: true
      
