apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: uinnlogget-kalkulator
  namespace: pensjonskalkulator
  labels:
    team:  pensjonskalkulator
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name:  pensjonskalkulator
  secretName:  uinnlogget-kalkulator-unleash-api-token
  environment: development
