import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@navikt/ds-css'
import { fetchDecoratorReact } from '@navikt/nav-dekoratoren-moduler/ssr'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const Decorator = await fetchDecoratorReact({
    env: 'prod',
    params: { context: 'arbeidsgiver', simple: true }
  } as any)

  return (
    <html lang='en'>
      <Decorator.Styles />
      <body className={inter.className}>
        <Decorator.Header />
        {children}
        <Decorator.Footer />
      </body>
    </html>
  )
}
