name: workflow-uinnlogget-dev
on:
  push:
    branches:
      - '**'
      - '!main'
      - '!magicbox'
      - '!dreambox'
      - '!catbox'
      

jobs:
  build:
    name: Bygg, test og publiser docker image
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.image-creation.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install npm dependencies
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      #Kode under er for å hente openapi schema fra backend og generere types
      # - name: Fetch openapi backend types
      #   run: npx openapi-typescript ${{ github.event.inputs.prod == 'true' && 'https://www.nav.no/pensjon/kalkulator/v3/api-docs/current' || 'https://staging.ekstern.dev.nav.no/pensjon/kalkulator/v3/api-docs/current' }} -o ./src/types/schema.d.ts
      # - name: Format backend scheme
      #   run: npm run format:types
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Build application
        run: npm run build